FROM node:22-alpine

# Instalar dependencias necesarias para Docker CLI
RUN apk update && \
    apk add docker-cli docker-cli-buildx bash git

# Crear un lugar de trabajo
WORKDIR /workspace

CMD ["bash"]
